name: Build Rojo Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rojo
        run: |
          wget https://github.com/rojo-rbx/rojo/releases/download/v7.2.0/rojo-7.2.0-linux.tar.gz
          tar -xzf rojo-7.2.0-linux.tar.gz
          sudo mv rojo /usr/local/bin/rojo
          sudo chmod +x /usr/local/bin/rojo

      - name: Build project
        run: rojo build -o "ObjectSerializer.rbxlx"
