name: Build Rojo Project

on:
  push:
    branches:
      - master  # Triggers on push to any branch
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rojo
        run: |
          ROJO_VERSION="7.2.1"  # Set the version you want to install
          wget https://github.com/rojo-rbx/rojo/releases/download/v7.4.1/rojo$ROJO_VERSION$-linux-x86_64.zip -O rojo
          chmod +x rojo
          sudo mv rojo /usr/local/bin/rojo

      - name: Build project
        run: rojo build -o "ObjectSerializer.rbxlx"
